version: '3.9'

services:
  admin:
    container_name: admin
    image: snak1o/shop_admin
    env_file:
      - ./frontend.env
  frontend:
    container_name: frontend
    image: snak1o/shop
    env_file:
      - ./frontend.env
  redis:
    container_name: redis
    image: redis:7-alpine
    env_file:
      - ./backend.env
    volumes:
      - $HOME/data/redis:/data
    command: redis-server --save 20 1 --loglevel warning
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - ./pgsql.env
    volumes:
      - $HOME/data/postgres:/var/lib/postgresql/data
  backend:
    container_name: backend
    image: hwndrer/backend
    env_file:
      - ./backend.env
      - ./pgsql.env
    environment:
      WAIT_HOSTS: postgres:5432, redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - $HOME/files:/app/files
  nginx:
    build: "./nginx"
    container_name: nginx
    ports:
      - "80:80"
      - "90:90"
    depends_on:
      - backend
      - frontend
    volumes:
      - $HOME/files:/var/files
